export const THROTTLE_TTL = 'THROTTLE_TTL';

export const THROTTLE_LIMIT = 'THROTTLE_LIMIT';

export const SALT_ROUND = 'SALT_ROUNDS';

export const JWT_SECRET = 'JWT_SECRET';

export const JWT_EXPIRES_IN = 'JWT_EXPIRES_IN';

export const AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID';

export const AWS_BUCKET_NAME = 'AWS_BUCKET_NAME';

export const AWS_S3_ENDPOINT = 'AWS_S3_ENDPOINT';

export const AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY';
export const AWS_S3_REGION = 'AWS_S3_REGION';
